imports:
  - { resource: common.yml }

services:
  _defaults:
    public: true

  prestashop.module.wnblocks.form.settings.general_data_configuration:
    class: 'PrestaShop\Module\WnBlocks\Form\Settings\GeneralDataConfiguration'
    arguments: [ '@prestashop.adapter.legacy.configuration', '@prestashop.adapter.shop.context' ]

  prestashop.module.wnblocks.form.settings.general_type:
    class: 'PrestaShop\Module\WnBlocks\Form\Settings\GeneralType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  prestashop.module.wnblocks.form.settings.general_form_data_provider:
    class: 'PrestaShop\Module\WnBlocks\Form\Settings\GeneralFormDataProvider'
    arguments:
      - '@prestashop.module.wnblocks.form.settings.general_data_configuration'

  prestashop.module.wnblocks.form.settings.general_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - "@form.factory"
      - "@prestashop.core.hook.dispatcher"
      - "@prestashop.module.wnblocks.form.settings.general_form_data_provider"
      - 'PrestaShop\Module\WnBlocks\Form\Settings\GeneralType'
      - "General"